### ISSUE TITLE
socketReadTimeout not assigned

### ISSUE THREAD

**Issue by steaerox** [sia-vpos/vpos-client-java-sdk#4]
The socketReadTimeout has not been correctly addressed on the right variable. That can be seen on VPosConfig Class. Please see the difference with Connection Timeout.

https://github.com/sia-vpos/vpos-client-java-sdk/blob/3f8605f68732b2d3732d8a86a4f173b4d1916fae/src/main/java/eu/sia/vpos/client/impl/VPosConfig.java#L68

Thank you in advance for support

**Comment by franrad16** [comment]
Fixed within version 1.2.2
Please let me know
Thank you

**Comment by steaerox** [comment]
It works fine now. Thank you too
